{
 "title": "Analytics",
 "tags": [ "SmartFactory" ],
 "time": { "from": "now-1y", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>Reason Codes Analysis</span>\n</div>\n\n\n\n"
  },
  {
   "title": "Pareto Chart - Reason Codes",
   "type": "smart-factory-pareto-reason-codes-bar-chart-panel",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"Site\", \"Area\", \"Line\", \"execute\", \"held\", \"idle\", \"stopped\", \"complete\", \"category\", \"reason\", \"comment\", \"parentReason\" FROM \"Availability\"  WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Reason Codes Frequency & Duration",
   "type": "smart-factory-pareto-reason-codes-pie-chart-panel",
   "gridPos": { "h": 11, "w": 14, "x": 0, "y": 14 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"Site\", \"Area\", \"Line\", \"execute\", \"held\", \"idle\", \"stopped\", \"complete\", \"category\", \"reason\", \"comment\", \"parentReason\" FROM \"Availability\"  WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Reason Codes Sunburst",
   "type": "smart-factory-pareto-reason-codes-sunburst-chart-panel",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 14 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"Site\", \"Area\", \"Line\", \"duration\", \"durationInt\", \"execute\", \"held\", \"idle\", \"stopped\", \"complete\", \"category\", \"reason\", \"comment\", \"parentReason\" FROM \"Availability\"  WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 25 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>QA Check History</span>\n</div>\n\n\n"
  },
  {
   "title": "QA History",
   "type": "smart-factory-qacheck-history-table-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "select * from process_control_form"
    }
   ]
  }
 ]
}