{
 "title": "Line Performance",
 "tags": [ "SmartFactory" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Site", "label": "Site", "query": "Select site from equipment" },
   {
    "name": "Area",
    "label": "Area",
    "query": "select area from equipment where area is not null and site = '$Site'"
   },
   {
    "name": "Line",
    "label": "Line",
    "query": "select production_line from equipment where production_line is not null and area = '$Area' and site = '$Site'"
   }
  ]
 },
 "panels": [
  {
   "title": "Current Running Order",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket:\"smart_factory/autogen\")  \n|> range(start: -50w)  \n|> filter(fn: (r) => r._measurement == \"OrderPerformance\")\n|> filter(fn: (r) => r._field == \"order_state\"or r._field==\"order_id\"or r._field==\"order_qty\"or r._field==\"order_date\"or r._field==\"order_state\"or r._field==\"production_line\"or r._field==\"scheduled_start_datetime\"or r._field==\"scheduled_end_datetime\"or r._field==\"planned_changeover_time\"or r._field==\"planned_rate\" or r._field==\"issued_qty\")\n|> last()\n|> fill(usePrevious: true)\n\n|> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n|> group(columns:[\"order_id\",\"product_id\",\"product_desc\"])\n\n|> filter(fn:(r) => r.production_line == \"$Site | $Area | $Line\")\n\n|> filter(fn:(r) => r.order_state == \"Running\")\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Planned Production",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT integral(\"planned_rate\",1s)/3600 FROM \"Performance\" WHERE $timeFilter and (\"Site\" = '$Site') and (\"Area\" = '$Area')  and (\"Line\" = '$Line') ",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Actual Production",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"actual_rate\") FROM \"Performance\" WHERE $timeFilter and (\"Site\" = '$Site') and (\"Area\" = '$Area')  and (\"Line\" = '$Line') ",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Held Time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 3 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"last\") FROM (SELECT last(\"held\") FROM \"Performance\" WHERE (\"Site\" = '$Site') and (\"Area\" = '$Area')  and (\"Line\" = '$Line') AND $timeFilter GROUP BY time(1s) fill(previous))",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Running Time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 3 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "measurement": "Performance",
     "query": "SELECT SUM(\"last\") FROM (SELECT last(\"execute\") FROM \"Performance\" WHERE (\"Site\" = '$Site') and (\"Area\" = '$Area')  and (\"Line\" = '$Line') AND $timeFilter GROUP BY time(1s) fill(previous))",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 3 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"execute\") / (SUM(\"held\")+SUM(\"execute\")) FROM (SELECT last(\"held\") AS held, last(\"execute\") AS execute FROM \"Performance\" WHERE (\"Site\" = '$Site') and (\"Area\" = '$Area')  and (\"Line\" = '$Line') AND $timeFilter GROUP BY time(1s) fill(previous))",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Performance",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 3 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT integral(\"actual_rate\",1s) / (integral(\"planned_rate\",1s) + integral(\"held\",1s)) FROM \"Performance\" WHERE $timeFilter and (\"Site\" = '$Site') and (\"Area\" = '$Area')  and (\"Line\" = '$Line') ",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Tasks",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \n count(1)\n\nFROM public.act_hi_procinst pi\n\nWHERE pi.state_='ACTIVE'"
    }
   ]
  },
  {
   "title": "Current Rate",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 5 },
   "targets": [
    {
     "measurement": "Performance",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n",
     "tags": [
      { "key": "Site", "operator": "=~", "value": "/^$Site$/" },
      { "condition": "AND", "key": "Area", "operator": "=~", "value": "/^$Area$/" },
      { "condition": "AND", "key": "Line", "operator": "=~", "value": "/^$Line$/" }
     ]
    }
   ]
  },
  {
   "title": "Line Performance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Performance",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n",
     "tags": [
      { "key": "Site", "operator": "=~", "value": "/^$Site$/" },
      { "condition": "AND", "key": "Area", "operator": "=~", "value": "/^$Area$/" },
      { "condition": "AND", "key": "Line", "operator": "=~", "value": "/^$Line$/" }
     ]
    },
    {
     "measurement": "Performance",
     "select": [
      [
       { "params": [ "actual_rate" ], "type": "field" },
       { "params": [ "actual_rate" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "Site", "operator": "=~", "value": "/^$Site$/" },
      { "condition": "AND", "key": "Area", "operator": "=~", "value": "/^$Area$/" },
      { "condition": "AND", "key": "Line", "operator": "=~", "value": "/^$Line$/" }
     ]
    }
   ]
  },
  {
   "title": "DownTime Editor Table",
   "type": "smart-factory-event-editor-table-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"Site\", \"Area\", \"Line\",\"MachineState\" as \"status\", \"execute\", \"held\", \"idle\", \"stopped\", \"complete\", \"category\", \"reason\", \"equipment\", \"comment\" FROM \"Performance\" WHERE $timeFilter and (\"Site\" = '$Site') and (\"Area\" = '$Area') and (\"Line\" = '$Line')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}