{
 "title": "Master Data",
 "tags": [ "SmartFactory" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Raw Material",
   "type": "libre-material-crud-table-panel",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "targets": [
    { "rawSql": "SELECT * from material" }
   ]
  },
  {
   "title": "Product Operation",
   "type": "libre-operation-crud-table-panel",
   "gridPos": { "h": 10, "w": 6, "x": 8, "y": 0 },
   "targets": [
    { "rawSql": "SELECT * FROM operation " }
   ]
  },
  {
   "title": "Product",
   "type": "libre-product-crud-table-panel",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT * FROM product"
    },
    { "rawSql": "SELECT * FROM product_group" },
    { "rawSql": "SELECT * FROM material" },
    { "rawSql": "SELECT * from operation\n" }
   ]
  },
  {
   "title": "Equipment",
   "type": "libre-equipment-crud-tree-chart-panel",
   "description": "Long click to add/edit/remove node.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "select * from equipment"
    }
   ]
  },
  {
   "title": "Reason Codes",
   "type": "libre-reason-codes-crud-tree-chart-panel",
   "description": "Long click to add/edit/remove node.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT * FROM reason_code"
    }
   ]
  }
 ]
}