{
 "title": "Scheduling",
 "tags": [ "SmartFactory" ],
 "time": { "from": "now/M", "to": "now/M" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Production Schedule Gantt Chart",
   "type": "smart-factory-production-schedule-gantt-chart-panel",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"order_date\", last(\"order_state\") as Status, \"order_qty\", \"planned_rate\", \"production_line\", \"scheduled_start_datetime\", \"scheduled_end_datetime\", \"planned_changeover_time\", \"compl_qty\", \"actual_start_datetime\", \"actual_end_datetime\", \"setpoint_rate\", \"product_desc\" FROM \"OrderPerformance\" WHERE $timeFilter GROUP BY \"order_id\", \"product_id\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Scheduler Order Management Table",
   "type": "smart-factory-scheduler-order-mgt-table-panel",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"order_date\", last(\"order_state\") as status, \"order_qty\", \"planned_rate\", \"planned_changeover_time\", \"production_line\", \"scheduled_start_datetime\", \"scheduled_end_datetime\", \"product_desc\" FROM \"OrderPerformance\" WHERE \"scheduled_start_datetime\" >= $__from AND \"scheduled_start_datetime\" <= $__to GROUP BY \"order_id\", \"product_id\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Production Line Start Time Setter",
   "type": "smart-factory-prod-line-time-setter-panel",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null) s",
     "rawSql": "SELECT distinct site, area, production_line, start_time FROM  equipment where area is not null and production_line is not null order by site asc, area asc, production_line desc"
    }
   ]
  }
 ]
}